### ISSUE TITLE
Add full extends support for services

### ISSUE THREAD

**Issue by russ-c** [kube-compose/kube-compose#48]
Currently extends only supports "environment" and "ports".

Full support for other configuration options should be added, see:
1. https://docs.docker.com/compose/extends/#adding-and-overriding-configuration
2. https://github.com/docker/compose/blob/master/compose/config/config.py#L1092

**Comment by jbrekelmans** [comment]
Narrowing down this issue to only options currently supported in kube-compose, as otherwise this would require cataloguing all possible fields of docker-compose. Much better to raise 1 issue for each docker compose field, and whene adding a new field also require that the merging logic is updated.
